<?php
declare (strict_types = 1);

namespace app\home\controller;

use app\home\HomeBase;

class Index extends HomeBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
       // return '您好！这是一个[home]示例应用';
        return view(
            "index",
            [
                "member_id"=>1
            ]
        );
    }
    function udpGet(){
        $sendMsg=json_encode(["parameters"=>[
            "port"=>10000,
            "version"=>"3.1",
        ]]);
        $handle = stream_socket_client("udp://192.168.1.14:10000", $errno, $errstr);
        if( !$handle ){
            die("ERROR: {$errno} - {$errstr}\n");
        }
        fwrite($handle, $sendMsg."\n");
        $result = fread($handle, 1024);
        fclose($handle);
    }
}
