<?php
/**
 *  Created by www.kuleiman.com.
 *  User: YaoHongQiang
 *  Date: 2021/6/2   14:52
 *  description:
 */

namespace app\home\controller;


use app\home\HomeBase;
use think\facade\View;

class xml extends HomeBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    function index(){
        View::config(['view_suffix' => 'xml']);
        return View::fetch();
    }
}