<?php
/**
 *  Created by www.kuleiman.com.
 *  User: YaoHongQiang
 *  Date: 2021/4/22   11:20
 *  description:
 */

namespace app\admin\controller;


use think\facade\View;

class Auth extends \app\BaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    function index(){
        return View::fetch();
    }
    function add(){

    }
}