<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\admin\AdminBase;

class Index extends AdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return '您好！这是一个[admin]示例应用';
    }
}
