<?php
/**
 *  Created by www.kuleiman.com.
 *  User: YaoHongQiang
 *  Date: 2021/4/20   15:36
 *  description:
 */

namespace app\admin\controller;


use app\admin\AdminBase;
use think\facade\View;

class Login extends AdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index(){
        return View::fetch();
    }
    function login(){
        $username=input("post.username/s","");
        $password=input("post.password/s","");
        if(!$username){
            $this->error("10000","请填写用户名");
        }
        if(!$password){
            $this->error("10000","请填写密码");
        }
    }
}