<?php
/**
 *  Created by www.kuleiman.com.
 *  User: YaoHongQiang
 *  Date: 2021/5/11   14:05
 *  description:
 */

namespace app\admin\controller;


use app\admin\AdminBase;
use think\facade\View;
use  app\admin\model\User as UserModel;
use app\admin\model\Auth;

class User extends AdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->UserModel=new UserModel();
    }
    function index(){
        $return_data=$this->UserModel->user_list();
        View::assign("list",$return_data["list"]);
        View::assign("page",$return_data["page"]);
        return View::fetch();
    }

    /**
     * 获取权限组
     */
    function auth_group(){
        $auth=new Auth();
        $data=$auth->auth_group("id,title");
        return $this->success("",["data"=>$data]);
    }
}